### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by emartynov** [alexjlockwood/kyrie#2]
Reading your blogpost I have two questions :)

The subj is the first one!

**Comment by emartynov** [comment]
Also found this https://github.com/alexjlockwood/kyrie/blob/master/library/src/main/java/com/github/alexjlockwood/kyrie/package-info.java

**Comment by alexjlockwood** [comment]
What is the question?

**Comment by emartynov** [comment]
Load/Use SVG instead of Vector drawables to fully support everything that designer tool created.

**Comment by alexjlockwood** [comment]
I think that is probably outside the scope of this project. This project aims to extend VectorDrawables and AnimatedVectorDrawables, not replace them with a brand new format. If you have any individual features from SVG that you think would be useful to add to this library, I'd be happy to consider that though. :)

**Comment by emartynov** [comment]
Clear. Thank you!
