### ISSUE TITLE
Programmatically sizing a vector drawable

### ISSUE THREAD

**Issue by jtlapp** [alexjlockwood/kyrie#22]
I am trying to load a bunch of vector drawables and set their size according to runtime requirements. Many have [sought this feature on stackoverflow over the years](https://www.google.com/search?q=programmatically+size+vectordrawable+site%3Astackoverflow.com), but it appears that Android can only do it while visible in a view.

Is it possible to scale a vector drawable with Kyrie?

If so, I'd love to see the code for it. You might also add it to your readme, and if you wanted more traction, maybe go through all those unanswered questions finally providing an answer!

**Comment by alexjlockwood** [comment]
I think you should be able to do this with just an `ImageView`? 

i.e. If you set the vector drawable on the `ImageView` and set the `ImageView`'s scale type to `fitCenter`, then you can programatically set the `ImageView`s width/height and the vector will scale accordingly.

This is how I would recommend doing it with Kyrie as well.

**Comment by jtlapp** [comment]
You can resize vector drawables in image views, but I need to resize hundreds of images in the background in preparation for rapid-fire display in the manner of a custom animation. The animation is complicated because there are pieces that I assemble as necessary; I need to control the animation myself. I also need to manipulate the vector drawables in other ways prior to animation (mainly cropping and positioning).

**Comment by jtlapp** [comment]
Or are you saying that I can somehow resize images efficiently in the background using ImageView, prior to presentation of any of the images?

**Comment by jtlapp** [comment]
Do you have any advice on where to dig in to Kyrie to go through transforming points and line widths? It sounds like I'll need to extend it for my own purposes. It looks like a great start though.

**Comment by alexjlockwood** [comment]
What is it you are trying to achieve exactly? What do you mean by "resize"? What type of "custom animation" is it? What are the "hundreds of images" being used for?

**Comment by jtlapp** [comment]
> What is it you are trying to achieve exactly? What do you mean by "resize"? What type of "custom animation" is it? What are the "hundreds of images" being used for?

Rendering animations of gestures that I'm asking the user to perform as part of a tutorial app. The gestures are all those possible using my [system for inputting text on a touch screen](http://josephtlapp.com/rapid/) faster than you can on a keyboard but without a keyboard.

There are many possible combinations of gestures. Each finger has many things it can do, and different fingers can work in combination, on either hand. I paid an animator to create SVG files of all the components that go into assembling the animations of these gestures. Now I need to dynamically assemble the gesture animations from their contributing vectors drawables.

**Comment by jtlapp** [comment]
Moreover, I need to be able to play the animations at different speeds to make the gestures clear. The animator made the animations smooth at the slowest possible speed, but I fear that playing all those frames at a faster speed will be too much for most devices, so I have a system for skipping all but pivotal frames as a means for increasing animation speed. I already have this speed control technique working in a TornadoFX app for the desktop with simple gestures.

**Comment by jtlapp** [comment]
The only alternative I can think of is to provide PNGs for everything in the highest possible resolution I might need and then dynamically shrink the PNGs in the background prior to assembling each gesture. But I fear:

1. This will eat a lot of clock cycles, waste battery, and take more time than recomputing the vector drawables and drawing them in series on a bitmap.
2. This will consume a lot more memory on the device.
3. The text won't turn out as readable as I'd like. I could however remove the text and render the text on top at runtime -- just an added complication.

**Comment by alexjlockwood** [comment]
Hmm... yeah, not sure. This sounds pretty complex and probably outside the scope of this library. I don't think this library has a specific feature that would make this any easier. 

I think to answer your specific question, it's easiest to scale `VectorDrawable`s and `KyrieDrawable`s via an `ImageView`. If the `ImageView` scale types don't work for you, you can arbitrarily transform (i.e. scale, translate, and/or rotate) the `ImageView`s drawable by passing a `Matrix` into `ImageView#setImageMatrix()`. You could potentially even animate this `Matrix` to achieve some cool effects (this is how [`ChangeImageTransform`](https://developer.android.com/reference/androidx/transition/ChangeImageTransform.html) works in the Android `Transition` library, for example).

You could also write a custom `View` and transform the `VectorDrawable` using `Canvas` operations in `onDraw()` too (which is essentially how [`ImageView` scale types](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/widget/ImageView.java#1350) work under-the-hood).

No clue if any of this is helpful at all...

**Comment by jtlapp** [comment]
That's quite helpful, thank you! I'm just learning Android, but somehow I assumed that an ImageView would only scale when rendered on the screen. Thanks for the avenues to explore.

I'll go ahead and close this, but will let you know of anything I end up doing with Kyrie.
