### ISSUE TITLE
Change hosting repository

### ISSUE THREAD

**Issue by MiSikora** [alexjlockwood/kyrie#29]
JFrog [announced](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter) yesterday that they will sunset JCenter May 1st. A migration to a different repository would be welcome.

**Comment by MiSikora** [comment]
@alexjlockwood Do you have plans to do this or should I resolve it in some other way? Not rushing :), just want to know if I have to do something else.

**Comment by AsynctaskCoffee** [comment]
Any news on this ?

**Comment by MiSikora** [comment]
I'm closing this one as JFrog kept JCenter as read only indefinitely.
