### ISSUE TITLE
can't import

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [alexjlockwood/kyrie#3]
I get this:

![image](https://user-images.githubusercontent.com/5357526/37258804-d3a881cc-2585-11e8-8a46-711c26c8158c.png)

**Comment by alexjlockwood** [comment]
What version of Android Studio are you using?

**Comment by alexjlockwood** [comment]
Did you change the gradle version when you imported the project?

Please provide the necessary information to reproduce the problem.

**Comment by AndroidDeveloperLB** [comment]
Tried stable version 3.0.1 and it still doesn't work:

![image](https://user-images.githubusercontent.com/5357526/37259062-20db5e7a-258a-11e8-83f6-021f29ec9f36.png)

Attached project.
[kyrie.zip](https://github.com/alexjlockwood/kyrie/files/1800945/kyrie.zip)

**Comment by AndroidDeveloperLB** [comment]
oh. you changed it. Now it works fine.
btw, there is already new version of the support library (27.1.0)
and, you don't have to specify buildToolsVersion anywhere anymore. It will always take the latest.

**Comment by alexjlockwood** [comment]
Cool, thanks for letting me know. I'll change it once Android Studio stable starts using the latest gradle release.
