### ISSUE TITLE
Apk is packaging png images for vector drawable

### ISSUE THREAD

**Issue by zincle** [alexjlockwood/kyrie#4]
Alex, I am using kyrie to show vector images in andorid imageview and my application's minimum os support version is 18, In My final build android is packaging pngs for every vector image added in every drawable folder and this is leading to increase in apk size, Is there any way I can prevent this automatic generation of raster PNG images for API level 20? I am not using android support appcompat and support vector drawable library.

**Comment by alexjlockwood** [comment]
Is this an issue specific to the library?

**Comment by alexjlockwood** [comment]
Please refer to this blog post: https://medium.com/@chrisbanes/appcompat-v23-2-age-of-the-vectors-91cbafa87c88

Specifically the part where the bost post explains why you need to set `vectorDrawables.useSupportLibrary = true` in your `build.gradle`.

I have a sample project with a bunch of vector drawable examples here if you need an example to look at: https://github.com/alexjlockwood/adp-delightful-details

**Comment by zincle** [comment]
No not an issue specific to the library, btw thanks, will check it out.
