### ISSUE TITLE
ImageView is cut when using KyrieDrawable

### ISSUE THREAD

**Issue by imhungnt** [alexjlockwood/kyrie#8]
Hi Alex,

I have an issue when using this library, the code below:

Layout.xml
  <ImageView
      android:id="@+id/image_view_pane3"
      android:layout_width="match_parent"
      android:layout_height="200dp"
      android:layout_marginBottom="8dp"
      android:layout_marginEnd="8dp"
      android:layout_marginStart="8dp"
      android:layout_marginTop="2dp"
      android:adjustViewBounds="true"
      android:layout_weight="1"
      tools:ignore="ContentDescription" />

Java file.
private ImageView imageViewLetterA;
...
imageViewLines = rootView.findViewById(R.id.image_view_pane3);
...
final KyrieDrawable lines = createLetterDrawable();
imageViewLines.setImageDrawable(lines);
...
private KyrieDrawable createLetterDrawable() {
        final KyrieDrawable.Builder builder =
                KyrieDrawable.builder().viewport(200, 200);
        // SVG path data objects.
       final PathData linesPathData = PathData.parse("M1.5,51.5 L150.5,51.5 M1.5,100.5 L150.5,100.5 M1.5,150.5 L150.5,150.5 M27.5,101.5 L27.5,199.5 M1.5,200.5 L150.5,200.5 M1.5,1.5 L150.5,1.5 M1.5,1.5 L1.5,200.5 M51.5,1.5 L51.5,200.5 M101.5,1.5 L101.5,200.5 M151,1.49937502 L151,200.500626");
        final Animation<PointF, PointF> pathMotion =
                Animation.ofPathMotion(PathData.toPath(linesPathData))
                        .repeatCount(0)
                        .duration(DURATION);
        builder.child(
                PathNode.builder()
                        .pathData(linesPathData)
                        .strokeWidth(10f)
                        .strokeLineCap(2)
                        .strokeLineJoin(2)
                        .strokeColor(Color.GRAY));
        builder.child(
                CircleNode.builder()
                        .fillColor(Color.RED)
                        .radius(8)
                        .centerX(pathMotion.transform(p -> p.x))
                        .centerY(pathMotion.transform(p -> p.y)));
        return builder.build();
    }

When i run the app, the lines on bottom and left side is cut to half, the CircleNode when moving along the lines is cut half when on bottom or left too.

![screenshot_15266348132](https://user-images.githubusercontent.com/16146326/40227700-6b08aac0-5ab9-11e8-89a9-f98249c025bf.png)

**Comment by alexjlockwood** [comment]
I am pretty sure this is working as intended. This library is meant to produce the same visual behavior of native `AndroidVectorDrawable`s.

For example, here is the `KyrieDrawable` you posted above:

```
  private KyrieDrawable createLetterDrawable() {
    final KyrieDrawable.Builder builder = KyrieDrawable.builder().viewport(200, 200);
    // SVG path data objects.
    final PathData linesPathData =
        PathData.parse(
            "M1.5,51.5 L150.5,51.5 M1.5,100.5 L150.5,100.5 M1.5,150.5 L150.5,150.5 M27.5,101.5 L27.5,199.5 M1.5,200.5 L150.5,200.5 M1.5,1.5 L150.5,1.5 M1.5,1.5 L1.5,200.5 M51.5,1.5 L51.5,200.5 M101.5,1.5 L101.5,200.5 M151,1.49937502 L151,200.500626");
    final Animation<PointF, PointF> pathMotion =
        Animation.ofPathMotion(PathData.toPath(linesPathData)).duration(15000);
    builder.child(
        PathNode.builder()
            .pathData(linesPathData)
            .strokeWidth(10f)
            .strokeLineCap(StrokeLineCap.SQUARE)
            .strokeLineJoin(StrokeLineJoin.BEVEL)
            .strokeColor(Color.GRAY));
    builder.child(
        CircleNode.builder()
            .fillColor(Color.RED)
            .radius(8)
            .centerX(pathMotion.transform(p -> p.x))
            .centerY(pathMotion.transform(p -> p.y)));
    return builder.build();
  }
```

and here is how you would express that same exact animation in `AnimatedVectorDrawable` form:

```
<animated-vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    xmlns:tools="http://schemas.android.com/tools"
    tools:ignore="NewApi">

    <aapt:attr name="android:drawable">
        <vector
            android:width="200dp"
            android:height="200dp"
            android:viewportWidth="200"
            android:viewportHeight="200">
            <path
                android:pathData="M1.5,51.5 L150.5,51.5 M1.5,100.5 L150.5,100.5 M1.5,150.5 L150.5,150.5 M27.5,101.5 L27.5,199.5 M1.5,200.5 L150.5,200.5 M1.5,1.5 L150.5,1.5 M1.5,1.5 L1.5,200.5 M51.5,1.5 L51.5,200.5 M101.5,1.5 L101.5,200.5 M151,1.49937502 L151,200.500626"
                android:strokeWidth="10"
                android:strokeLineJoin="bevel"
                android:strokeLineCap="square"
                android:strokeColor="#888888" />
            <group android:name="group">
                <path
                    android:fillColor="#f00"
                    android:pathData=" M 0 0 m -8 0 a 8 8 0 1 0 16 0 a 8 8 0 1 0 -16 0 z" />
            </group>
        </vector>
    </aapt:attr>

    <target android:name="group">
        <aapt:attr name="android:animation">
            <objectAnimator
                android:duration="15000"
                android:interpolator="@android:interpolator/linear"
                android:pathData="M1.5,51.5 L150.5,51.5 M1.5,100.5 L150.5,100.5 M1.5,150.5 L150.5,150.5 M27.5,101.5 L27.5,199.5 M1.5,200.5 L150.5,200.5 M1.5,1.5 L150.5,1.5 M1.5,1.5 L1.5,200.5 M51.5,1.5 L51.5,200.5 M101.5,1.5 L101.5,200.5 M151,1.49937502 L151,200.500626"
                android:propertyXName="translateX"
                android:propertyYName="translateY" />
        </aapt:attr>
    </target>

</animated-vector>
```

I think the issue is that your viewport is too small. For example, if you add `10` to the viewport in each direction (i.e. change the viewport from `200` to `220` and add a `GroupNode` that translates the entire image by `10` so that it remains centered), such as:

```
  private KyrieDrawable createLetterDrawable() {
    final KyrieDrawable.Builder builder = KyrieDrawable.builder().viewport(220, 220);
    final PathData linesPathData =
        PathData.parse(
            "M1.5,51.5 L150.5,51.5 M1.5,100.5 L150.5,100.5 M1.5,150.5 L150.5,150.5 M27.5,101.5 L27.5,199.5 M1.5,200.5 L150.5,200.5 M1.5,1.5 L150.5,1.5 M1.5,1.5 L1.5,200.5 M51.5,1.5 L51.5,200.5 M101.5,1.5 L101.5,200.5 M151,1.49937502 L151,200.500626");
    final Animation<PointF, PointF> pathMotion =
        Animation.ofPathMotion(PathData.toPath(linesPathData)).duration(15000);
    builder.child(
        GroupNode.builder()
            .translateX(10)
            .translateY(10)
            .child(
                PathNode.builder()
                    .pathData(linesPathData)
                    .strokeWidth(10f)
                    .strokeLineCap(StrokeLineCap.SQUARE)
                    .strokeLineJoin(StrokeLineJoin.BEVEL)
                    .strokeColor(Color.GRAY))
            .child(
                CircleNode.builder()
                    .fillColor(Color.RED)
                    .radius(8)
                    .centerX(pathMotion.transform(p -> p.x))
                    .centerY(pathMotion.transform(p -> p.y))));
    return builder.build();
  }
```

then you can get something that looks like this:

![screenshot_1526751184](https://user-images.githubusercontent.com/1380747/40271301-723c9030-5b69-11e8-80be-7f60f6d63e02.png)

**Comment by imhungnt** [comment]
Yes, thank you very much!
